apiVersion: v1
data:
  FLUENTD_HOST: fluentd.dso-dgcre.svc.cluster.local
  FLUENTD_PORT: '24224'
  APP_LOGGING_LEVEL: DEBUG
  SOAP_CONNECTION_TIMEOUT: 10s
  SOAP_READ_TIMEOUT: 10s
  HERMES_NOTIFICATION_ENDPOINT_URL: http://k3-hermes-app.msk.vtb24.ru/Hermes/Services
  SERVICE_MOCK_ENABLED: 'true'
  SPRING_ACTIVE_PROFILE: openshift
kind: ConfigMap
metadata:
  name: integration-hermes-subscription